assertion_consumer_service_url: https://identity-rp-demo.apps.cloud.gov/consume
assertion_consumer_service_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
issuer: urn:gov:gsa:SAML:2.0.profiles:sp:sso:demo
idp_sso_target_url: https://upaya-idp-demo.18f.gov/api/saml/auth
idp_slo_target_url: https://upaya-idp-demo.18f.gov/api/saml/logout
idp_cert_fingerprint: 8B:D5:C2:E8:9A:2B:CE:B7:4B:95:50:BA:16:79:05:27:17:D1:D3:67
name_identifier_format: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
authn_context: http://idmanagement.gov/ns/assurance/loa/1
single_signon_service_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
allowed_clock_drift: 60
security:
  authn_requests_signed: true
  embed_sign: true
  digest_method: http://www.w3.org/2001/04/xmlenc#sha256
  signature_method: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
